name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04-16core

    steps:
      - uses: actions/checkout@v2
      - name: Check KVM 
        run: |
            echo "test"
            egrep -c "svm|vmx" /proc/cpuinfo
            df -h
            free -h
            lscpu
        
